service: bus-sizes-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  # profile: serverless
  apiGateway:
    shouldStartNameWithService: true

plugins:
  - serverless-offline

functions:
  sizes:
    handler: handler.sizes
    events:
      - http:
          method: POST
          path: /sizes